@extends('layouts.app')

@section('title', 'Registrar compra')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Registrar compra</h1><a href="{{ route('admin.compras.index') }}" class="btn btn-outline-secondary">Volver</a></div>
<form method="POST" action="{{ route('admin.compras.store') }}">@csrf
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><label for="id_proveedor" class="form-label">Proveedor</label><select id="id_proveedor" name="id_proveedor" class="form-select @error('id_proveedor') is-invalid @enderror" required><option value="">Seleccionar proveedor...</option>@foreach($proveedores as $proveedor)<option value="{{ $proveedor->id_proveedor }}" @selected(old('id_proveedor') == $proveedor->id_proveedor)>{{ $proveedor->nombre_proveedor }}</option>@endforeach</select>@error('id_proveedor')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between align-items-center"><h2 class="h5 mb-0">Medicamentos</h2><button type="button" id="agregarDetalle" class="btn btn-sm btn-outline-primary">Agregar medicamento</button></div><div class="card-body"><div id="detalles">
<div class="row g-2 align-items-end detalle-item mb-3"><div class="col-md-5"><label class="form-label">Medicamento</label><select name="detalles[0][id_medicamento]" class="form-select" required><option value="">Seleccionar...</option>@foreach($medicamentos as $medicamento)<option value="{{ $medicamento->id_medicamento }}">{{ $medicamento->nombre }} (stock: {{ $medicamento->stock }})</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Cantidad</label><input name="detalles[0][cantidad]" type="number" min="1" class="form-control" required></div><div class="col-md-3"><label class="form-label">Precio de compra</label><input name="detalles[0][precio_compra]" type="number" min="0" step="0.01" class="form-control" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger quitarDetalle" disabled>Quitar</button></div></div>
</div></div><div class="card-footer bg-white d-flex justify-content-end"><button class="btn btn-primary">Confirmar compra</button></div></div></form>
<template id="detalleTemplate"><div class="row g-2 align-items-end detalle-item mb-3"><div class="col-md-5"><label class="form-label">Medicamento</label><select name="detalles[__INDEX__][id_medicamento]" class="form-select" required><option value="">Seleccionar...</option>@foreach($medicamentos as $medicamento)<option value="{{ $medicamento->id_medicamento }}">{{ $medicamento->nombre }} (stock: {{ $medicamento->stock }})</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Cantidad</label><input name="detalles[__INDEX__][cantidad]" type="number" min="1" class="form-control" required></div><div class="col-md-3"><label class="form-label">Precio de compra</label><input name="detalles[__INDEX__][precio_compra]" type="number" min="0" step="0.01" class="form-control" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger quitarDetalle">Quitar</button></div></div></template>
@push('scripts')<script>document.addEventListener('DOMContentLoaded', () => { const contenedor = document.querySelector('#detalles'); const plantilla = document.querySelector('#detalleTemplate').innerHTML; let indice = 1; document.querySelector('#agregarDetalle').addEventListener('click', () => { contenedor.insertAdjacentHTML('beforeend', plantilla.replaceAll('__INDEX__', indice++)); }); contenedor.addEventListener('click', (evento) => { if (evento.target.classList.contains('quitarDetalle') && document.querySelectorAll('.detalle-item').length > 1) evento.target.closest('.detalle-item').remove(); }); });</script>@endpush
@endsection
