@extends('layouts.app')

@section('title', $modo . ' medicamento')

@section('content')
<div class="row justify-content-center"><div class="col-lg-9"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h1 class="h3 mb-4">{{ $modo }} medicamento</h1><form method="POST" action="{{ $medicamento->exists ? route('admin.medicamentos.update', $medicamento) : route('admin.medicamentos.store') }}">@csrf @if($medicamento->exists) @method('PUT') @endif
<div class="mb-3"><label for="nombre" class="form-label">Nombre</label><input id="nombre" name="nombre" value="{{ old('nombre', $medicamento->nombre) }}" class="form-control @error('nombre') is-invalid @enderror" required maxlength="160">@error('nombre')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="row"><div class="col-md-6 mb-3"><label for="precio_compra" class="form-label">Precio de compra</label><input id="precio_compra" name="precio_compra" type="number" step="0.01" min="0" value="{{ old('precio_compra', $medicamento->precio_compra) }}" class="form-control @error('precio_compra') is-invalid @enderror" required>@error('precio_compra')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-3"><label for="precio_venta" class="form-label">Precio de venta</label><input id="precio_venta" name="precio_venta" type="number" step="0.01" min="0" value="{{ old('precio_venta', $medicamento->precio_venta) }}" class="form-control @error('precio_venta') is-invalid @enderror" required>@error('precio_venta')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="row"><div class="col-md-4 mb-3"><label for="stock" class="form-label">Stock</label><input id="stock" name="stock" type="number" min="0" value="{{ old('stock', $medicamento->stock ?? 0) }}" class="form-control @error('stock') is-invalid @enderror" required>@error('stock')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4 mb-3"><label for="fecha_vencimiento" class="form-label">Fecha de vencimiento</label><input id="fecha_vencimiento" name="fecha_vencimiento" type="date" value="{{ old('fecha_vencimiento', optional($medicamento->fecha_vencimiento)->format('Y-m-d')) }}" class="form-control @error('fecha_vencimiento') is-invalid @enderror" required>@error('fecha_vencimiento')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4 mb-4"><label for="id_categoria" class="form-label">Categoría</label><select id="id_categoria" name="id_categoria" class="form-select @error('id_categoria') is-invalid @enderror" required><option value="">Seleccionar...</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id_categoria }}" @selected(old('id_categoria', $medicamento->id_categoria) == $categoria->id_categoria)>{{ $categoria->nombre }}</option>@endforeach</select>@error('id_categoria')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<a href="{{ route('admin.medicamentos.index') }}" class="btn btn-outline-secondary">Cancelar</a> <button class="btn btn-primary">Guardar</button></form></div></div></div></div>
@endsection
