@extends('layouts.app')

@section('title', 'Medicamentos')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Medicamentos</h1><a href="{{ route('admin.medicamentos.create') }}" class="btn btn-primary">Nuevo medicamento</a></div>
<form class="row g-2 mb-3" method="GET"><div class="col-md-6"><input name="buscar" value="{{ request('buscar') }}" class="form-control" placeholder="Buscar medicamento o categoría"></div><div class="col-md-4"><select name="estado" class="form-select"><option value="">Todos los estados</option><option value="activos" @selected(request('estado') === 'activos')>Activos</option><option value="inactivos" @selected(request('estado') === 'inactivos')>Inactivos</option></select></div><div class="col-md-2 d-grid"><button class="btn btn-outline-primary">Filtrar</button></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Medicamento</th><th>Categoría</th><th>Precio venta</th><th>Stock</th><th>Vencimiento</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
@forelse ($medicamentos as $medicamento)<tr><td>{{ $medicamento->nombre }}</td><td>{{ $medicamento->categoria->nombre }}</td><td>{{ number_format((float) $medicamento->precio_venta, 2) }}</td><td><span class="badge text-bg-{{ $medicamento->stock <= config('farmacia.stock_bajo') ? 'warning' : 'success' }}">{{ $medicamento->stock }}</span></td><td>{{ $medicamento->fecha_vencimiento->format('d/m/Y') }}</td><td><span class="badge text-bg-{{ $medicamento->activo ? 'success' : 'secondary' }}">{{ $medicamento->activo ? 'Activo' : 'Inactivo' }}</span></td><td class="text-end"><a href="{{ route('admin.medicamentos.edit', $medicamento) }}" class="btn btn-sm btn-outline-primary">Editar</a>@if ($medicamento->activo)<form class="d-inline" method="POST" action="{{ route('admin.medicamentos.destroy', $medicamento) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('¿Desactivar este medicamento?')">Desactivar</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-4">No hay medicamentos registrados.</td></tr>@endforelse
</tbody></table></div><div class="card-footer bg-white">{{ $medicamentos->links() }}</div></div>
@endsection
