@extends('layouts.app')

@section('title', $modo . ' usuario')

@section('content')
<div class="row justify-content-center"><div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-body p-4"><h1 class="h3 mb-4">{{ $modo }} usuario</h1><form method="POST" action="{{ $usuario->exists ? route('admin.usuarios.update', $usuario) : route('admin.usuarios.store') }}">@csrf @if($usuario->exists) @method('PUT') @endif
<div class="mb-3"><label for="nombre" class="form-label">Nombre completo</label><input id="nombre" name="nombre" value="{{ old('nombre', $usuario->nombre) }}" class="form-control @error('nombre') is-invalid @enderror" required maxlength="120">@error('nombre')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3"><label for="email" class="form-label">Correo electrónico</label><input id="email" name="email" type="email" value="{{ old('email', $usuario->email) }}" class="form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="row"><div class="col-md-6 mb-3"><label for="password" class="form-label">Contraseña @if($usuario->exists)<span class="text-secondary">(opcional)</span>@endif</label><input id="password" name="password" type="password" autocomplete="new-password" minlength="8" class="form-control @error('password') is-invalid @enderror" @required(! $usuario->exists)>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-3"><label for="password_confirmation" class="form-label">Confirmar contraseña</label><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" minlength="8" class="form-control @error('password_confirmation') is-invalid @enderror" @required(! $usuario->exists)>@error('password_confirmation')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="row"><div class="col-md-6 mb-4"><label for="id_rol" class="form-label">Rol</label><select id="id_rol" name="id_rol" class="form-select @error('id_rol') is-invalid @enderror" required><option value="">Seleccionar...</option>@foreach($roles as $rol)<option value="{{ $rol->id_rol }}" @selected(old('id_rol', $usuario->id_rol) == $rol->id_rol)>{{ $rol->nombre }}</option>@endforeach</select>@error('id_rol')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-4"><label for="activo" class="form-label">Estado</label><select id="activo" name="activo" class="form-select"><option value="1" @selected(old('activo', $usuario->exists ? (int) $usuario->activo : 1) == 1)>Activo</option><option value="0" @selected(old('activo', $usuario->exists ? (int) $usuario->activo : 1) == 0)>Inactivo</option></select></div></div>
<a href="{{ route('admin.usuarios.index') }}" class="btn btn-outline-secondary">Cancelar</a> <button class="btn btn-primary">Guardar</button></form></div></div></div></div>
@endsection
